require_relative 'udap_security/authorization_code_group'
require_relative 'udap_security/client_credentials_group'

module UDAPSecurity
  class Suite < Inferno::TestSuite
    id :udap_security
    title 'UDAP Security'
    description %(
      The User Data Access Protocol (UDAP) Security test kit verifies that systems correctly implement the
      [UDAP Security IG](http://hl7.org/fhir/us/udap-security/STU1/)
      for extending OAuth 2.0 using UDAP workflows.

      There are three steps to the workflow:
      1. Discovery
      2. Dynamic Client Registration
      3. Authorization & Authentication

      These steps are grouped by the OAuth2.0 flow being tested:
      1. Authorization Code flow, which supports consumer-facing or Business-to-Business (B2B) use cases
      2. Client Credentials flow, which only supports the B2B use case

      Testers may test one or both flows based on their system under test.

      Dynamic Client Registration tests require clients to provide a unique X.509 certificate (trusted by the
      authorization server under test) for _each_ run of the registration tests.
      Testers have the option of generating and providing their own certificate(s) OR using certificates
      auto-generated by the Inferno tests.
    )

    input_instructions %(
      If using auto-generated client certificates, testers may provide their own signing cert (and its associated
      private key) as test inputs OR use Inferno's default self-signed certificate authority that is generated with the
      test kit.

      Either way, the authorization server under test MUST be configured to trust the signing certificate before Dynamic
      Client Registration tests are run.

      The default Inferno CA can be downloaded as a PEM file at the following link:
      * `#{Inferno::Application[:base_url]}/custom/udap_security/inferno_ca.pem`
    )

    cert_file = File.read(File.join(File.dirname(__FILE__), 'udap_security/certs/InfernoCA.pem'))
    cert_file_route_handler = proc { [200, { 'Content-Type' => 'application/x-pem-file' }, [cert_file]] }

    route(:get, '/inferno_ca.pem', cert_file_route_handler)

    resume_test_route :get, '/redirect' do |request|
      request.query_parameters['state']
    end

    group from: :udap_authorization_code_group
    group from: :udap_client_credentials_group
  end
end
